### PR TITLE
Introduced 6to5 to the build process

### PR DESCRIPTION
**Pull request by chadhietala**
I started moving `ember-metal` to make use of things like arrow functions, rest params, and template strings.

### CODE REVIEW

**Comment by rwjblue** [comment]
My main concern is that the output remain ES3 compatible.  We had to jump through many hoops with Esperanto to ensure that, so we need to be careful what transformations we use and if their output is ES3 compatible. 

I think I would prefer to use a whitelist of features (instead of a blacklist) so each feature can be vetted to ensure ES3 safety.  Is that possible?

**Comment by chadhietala** [comment]
Yea that makes sense.  The ones I added I'm pretty positive are safe. Need to check if object literal shorthand is ES3 safe.

**Comment by stefanpenner** [comment]
whats the build-time perf hit?

**Comment by rwjblue** [comment]
@stefanpenner - I haven't tested it just yet, but plan to after the 1.10/1.11-beta.1 ships have sailed.

**Comment by stefanpenner** [comment]
The object literal short hand should be fine if it's just functions not get/set

**Comment by rwjblue** [comment]
Initial build is roughly double, incremental is roughly the same.

https://gist.github.com/rwjblue/b3cbbac1236f34eabbda

**Comment by rwjblue** [comment]
I rebased, updated, and added a test in https://github.com/emberjs/emberjs-build/pull/75.

**Pull request closed without merging**
