### PR TITLE
Use ESLint internally

### PR DESCRIPTION
**Pull request by Turbo87**
... instead of JSHint

/cc @stefanpenner

### CODE REVIEW

**Comment by Turbo87** [comment]
the TravisCI failure seems to be an NPM caching issue. works fine here locally.

**Comment by Turbo87** [comment]
test timeout seems to be unrelated to these changes and will be fixed in a separate PR

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner can we get this PR merged first before implementing external ESLint usage?

**Comment by rwjblue** [comment]
Yep, seems good!

**Pull request merged**
