### PR TITLE
Embed current enabled features in build.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by twokul** [comment]
@rwjblue I will pull this in after I finish work on symlinks.

**Comment by rwjblue** [comment]
@twokul - Not really sure why we would block this on that, also just rebased.

**Comment by twokul** [comment]
@rwjblue I don't think master works with ember right now :disappointed:

**Comment by rwjblue** [comment]
@twokul yeah, I'm seeing that while trying to integrate

**Comment by twokul** [comment]
@rwjblue I probably broke it, I'm gonna work on support symlinks today.

**Comment by rwjblue** [comment]
Fixed failing test.  #50 fixed Ember build.

**Pull request merged**
